# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kim/Documents/Koivisto

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kim/Documents/Koivisto

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kim/Documents/Koivisto/CMakeFiles /home/kim/Documents/Koivisto/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kim/Documents/Koivisto/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Koivisto

# Build rule for target.
Koivisto: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Koivisto
.PHONY : Koivisto

# fast build rule for target.
Koivisto/fast:
	$(MAKE) -f CMakeFiles/Koivisto.dir/build.make CMakeFiles/Koivisto.dir/build
.PHONY : Koivisto/fast

src_files/Bitboard.o: src_files/Bitboard.cpp.o

.PHONY : src_files/Bitboard.o

# target to build an object file
src_files/Bitboard.cpp.o:
	$(MAKE) -f CMakeFiles/Koivisto.dir/build.make CMakeFiles/Koivisto.dir/src_files/Bitboard.cpp.o
.PHONY : src_files/Bitboard.cpp.o

src_files/Bitboard.i: src_files/Bitboard.cpp.i

.PHONY : src_files/Bitboard.i

# target to preprocess a source file
src_files/Bitboard.cpp.i:
	$(MAKE) -f CMakeFiles/Koivisto.dir/build.make CMakeFiles/Koivisto.dir/src_files/Bitboard.cpp.i
.PHONY : src_files/Bitboard.cpp.i

src_files/Bitboard.s: src_files/Bitboard.cpp.s

.PHONY : src_files/Bitboard.s

# target to generate assembly for a file
src_files/Bitboard.cpp.s:
	$(MAKE) -f CMakeFiles/Koivisto.dir/build.make CMakeFiles/Koivisto.dir/src_files/Bitboard.cpp.s
.PHONY : src_files/Bitboard.cpp.s

src_files/Board.o: src_files/Board.cpp.o

.PHONY : src_files/Board.o

# target to build an object file
src_files/Board.cpp.o:
	$(MAKE) -f CMakeFiles/Koivisto.dir/build.make CMakeFiles/Koivisto.dir/src_files/Board.cpp.o
.PHONY : src_files/Board.cpp.o

src_files/Board.i: src_files/Board.cpp.i

.PHONY : src_files/Board.i

# target to preprocess a source file
src_files/Board.cpp.i:
	$(MAKE) -f CMakeFiles/Koivisto.dir/build.make CMakeFiles/Koivisto.dir/src_files/Board.cpp.i
.PHONY : src_files/Board.cpp.i

src_files/Board.s: src_files/Board.cpp.s

.PHONY : src_files/Board.s

# target to generate assembly for a file
src_files/Board.cpp.s:
	$(MAKE) -f CMakeFiles/Koivisto.dir/build.make CMakeFiles/Koivisto.dir/src_files/Board.cpp.s
.PHONY : src_files/Board.cpp.s

src_files/History.o: src_files/History.cpp.o

.PHONY : src_files/History.o

# target to build an object file
src_files/History.cpp.o:
	$(MAKE) -f CMakeFiles/Koivisto.dir/build.make CMakeFiles/Koivisto.dir/src_files/History.cpp.o
.PHONY : src_files/History.cpp.o

src_files/History.i: src_files/History.cpp.i

.PHONY : src_files/History.i

# target to preprocess a source file
src_files/History.cpp.i:
	$(MAKE) -f CMakeFiles/Koivisto.dir/build.make CMakeFiles/Koivisto.dir/src_files/History.cpp.i
.PHONY : src_files/History.cpp.i

src_files/History.s: src_files/History.cpp.s

.PHONY : src_files/History.s

# target to generate assembly for a file
src_files/History.cpp.s:
	$(MAKE) -f CMakeFiles/Koivisto.dir/build.make CMakeFiles/Koivisto.dir/src_files/History.cpp.s
.PHONY : src_files/History.cpp.s

src_files/Move.o: src_files/Move.cpp.o

.PHONY : src_files/Move.o

# target to build an object file
src_files/Move.cpp.o:
	$(MAKE) -f CMakeFiles/Koivisto.dir/build.make CMakeFiles/Koivisto.dir/src_files/Move.cpp.o
.PHONY : src_files/Move.cpp.o

src_files/Move.i: src_files/Move.cpp.i

.PHONY : src_files/Move.i

# target to preprocess a source file
src_files/Move.cpp.i:
	$(MAKE) -f CMakeFiles/Koivisto.dir/build.make CMakeFiles/Koivisto.dir/src_files/Move.cpp.i
.PHONY : src_files/Move.cpp.i

src_files/Move.s: src_files/Move.cpp.s

.PHONY : src_files/Move.s

# target to generate assembly for a file
src_files/Move.cpp.s:
	$(MAKE) -f CMakeFiles/Koivisto.dir/build.make CMakeFiles/Koivisto.dir/src_files/Move.cpp.s
.PHONY : src_files/Move.cpp.s

src_files/MoveOrderer.o: src_files/MoveOrderer.cpp.o

.PHONY : src_files/MoveOrderer.o

# target to build an object file
src_files/MoveOrderer.cpp.o:
	$(MAKE) -f CMakeFiles/Koivisto.dir/build.make CMakeFiles/Koivisto.dir/src_files/MoveOrderer.cpp.o
.PHONY : src_files/MoveOrderer.cpp.o

src_files/MoveOrderer.i: src_files/MoveOrderer.cpp.i

.PHONY : src_files/MoveOrderer.i

# target to preprocess a source file
src_files/MoveOrderer.cpp.i:
	$(MAKE) -f CMakeFiles/Koivisto.dir/build.make CMakeFiles/Koivisto.dir/src_files/MoveOrderer.cpp.i
.PHONY : src_files/MoveOrderer.cpp.i

src_files/MoveOrderer.s: src_files/MoveOrderer.cpp.s

.PHONY : src_files/MoveOrderer.s

# target to generate assembly for a file
src_files/MoveOrderer.cpp.s:
	$(MAKE) -f CMakeFiles/Koivisto.dir/build.make CMakeFiles/Koivisto.dir/src_files/MoveOrderer.cpp.s
.PHONY : src_files/MoveOrderer.cpp.s

src_files/Perft.o: src_files/Perft.cpp.o

.PHONY : src_files/Perft.o

# target to build an object file
src_files/Perft.cpp.o:
	$(MAKE) -f CMakeFiles/Koivisto.dir/build.make CMakeFiles/Koivisto.dir/src_files/Perft.cpp.o
.PHONY : src_files/Perft.cpp.o

src_files/Perft.i: src_files/Perft.cpp.i

.PHONY : src_files/Perft.i

# target to preprocess a source file
src_files/Perft.cpp.i:
	$(MAKE) -f CMakeFiles/Koivisto.dir/build.make CMakeFiles/Koivisto.dir/src_files/Perft.cpp.i
.PHONY : src_files/Perft.cpp.i

src_files/Perft.s: src_files/Perft.cpp.s

.PHONY : src_files/Perft.s

# target to generate assembly for a file
src_files/Perft.cpp.s:
	$(MAKE) -f CMakeFiles/Koivisto.dir/build.make CMakeFiles/Koivisto.dir/src_files/Perft.cpp.s
.PHONY : src_files/Perft.cpp.s

src_files/TimeManager.o: src_files/TimeManager.cpp.o

.PHONY : src_files/TimeManager.o

# target to build an object file
src_files/TimeManager.cpp.o:
	$(MAKE) -f CMakeFiles/Koivisto.dir/build.make CMakeFiles/Koivisto.dir/src_files/TimeManager.cpp.o
.PHONY : src_files/TimeManager.cpp.o

src_files/TimeManager.i: src_files/TimeManager.cpp.i

.PHONY : src_files/TimeManager.i

# target to preprocess a source file
src_files/TimeManager.cpp.i:
	$(MAKE) -f CMakeFiles/Koivisto.dir/build.make CMakeFiles/Koivisto.dir/src_files/TimeManager.cpp.i
.PHONY : src_files/TimeManager.cpp.i

src_files/TimeManager.s: src_files/TimeManager.cpp.s

.PHONY : src_files/TimeManager.s

# target to generate assembly for a file
src_files/TimeManager.cpp.s:
	$(MAKE) -f CMakeFiles/Koivisto.dir/build.make CMakeFiles/Koivisto.dir/src_files/TimeManager.cpp.s
.PHONY : src_files/TimeManager.cpp.s

src_files/TranspositionTable.o: src_files/TranspositionTable.cpp.o

.PHONY : src_files/TranspositionTable.o

# target to build an object file
src_files/TranspositionTable.cpp.o:
	$(MAKE) -f CMakeFiles/Koivisto.dir/build.make CMakeFiles/Koivisto.dir/src_files/TranspositionTable.cpp.o
.PHONY : src_files/TranspositionTable.cpp.o

src_files/TranspositionTable.i: src_files/TranspositionTable.cpp.i

.PHONY : src_files/TranspositionTable.i

# target to preprocess a source file
src_files/TranspositionTable.cpp.i:
	$(MAKE) -f CMakeFiles/Koivisto.dir/build.make CMakeFiles/Koivisto.dir/src_files/TranspositionTable.cpp.i
.PHONY : src_files/TranspositionTable.cpp.i

src_files/TranspositionTable.s: src_files/TranspositionTable.cpp.s

.PHONY : src_files/TranspositionTable.s

# target to generate assembly for a file
src_files/TranspositionTable.cpp.s:
	$(MAKE) -f CMakeFiles/Koivisto.dir/build.make CMakeFiles/Koivisto.dir/src_files/TranspositionTable.cpp.s
.PHONY : src_files/TranspositionTable.cpp.s

src_files/Tuning.o: src_files/Tuning.cpp.o

.PHONY : src_files/Tuning.o

# target to build an object file
src_files/Tuning.cpp.o:
	$(MAKE) -f CMakeFiles/Koivisto.dir/build.make CMakeFiles/Koivisto.dir/src_files/Tuning.cpp.o
.PHONY : src_files/Tuning.cpp.o

src_files/Tuning.i: src_files/Tuning.cpp.i

.PHONY : src_files/Tuning.i

# target to preprocess a source file
src_files/Tuning.cpp.i:
	$(MAKE) -f CMakeFiles/Koivisto.dir/build.make CMakeFiles/Koivisto.dir/src_files/Tuning.cpp.i
.PHONY : src_files/Tuning.cpp.i

src_files/Tuning.s: src_files/Tuning.cpp.s

.PHONY : src_files/Tuning.s

# target to generate assembly for a file
src_files/Tuning.cpp.s:
	$(MAKE) -f CMakeFiles/Koivisto.dir/build.make CMakeFiles/Koivisto.dir/src_files/Tuning.cpp.s
.PHONY : src_files/Tuning.cpp.s

src_files/Util.o: src_files/Util.cpp.o

.PHONY : src_files/Util.o

# target to build an object file
src_files/Util.cpp.o:
	$(MAKE) -f CMakeFiles/Koivisto.dir/build.make CMakeFiles/Koivisto.dir/src_files/Util.cpp.o
.PHONY : src_files/Util.cpp.o

src_files/Util.i: src_files/Util.cpp.i

.PHONY : src_files/Util.i

# target to preprocess a source file
src_files/Util.cpp.i:
	$(MAKE) -f CMakeFiles/Koivisto.dir/build.make CMakeFiles/Koivisto.dir/src_files/Util.cpp.i
.PHONY : src_files/Util.cpp.i

src_files/Util.s: src_files/Util.cpp.s

.PHONY : src_files/Util.s

# target to generate assembly for a file
src_files/Util.cpp.s:
	$(MAKE) -f CMakeFiles/Koivisto.dir/build.make CMakeFiles/Koivisto.dir/src_files/Util.cpp.s
.PHONY : src_files/Util.cpp.s

src_files/eval.o: src_files/eval.cpp.o

.PHONY : src_files/eval.o

# target to build an object file
src_files/eval.cpp.o:
	$(MAKE) -f CMakeFiles/Koivisto.dir/build.make CMakeFiles/Koivisto.dir/src_files/eval.cpp.o
.PHONY : src_files/eval.cpp.o

src_files/eval.i: src_files/eval.cpp.i

.PHONY : src_files/eval.i

# target to preprocess a source file
src_files/eval.cpp.i:
	$(MAKE) -f CMakeFiles/Koivisto.dir/build.make CMakeFiles/Koivisto.dir/src_files/eval.cpp.i
.PHONY : src_files/eval.cpp.i

src_files/eval.s: src_files/eval.cpp.s

.PHONY : src_files/eval.s

# target to generate assembly for a file
src_files/eval.cpp.s:
	$(MAKE) -f CMakeFiles/Koivisto.dir/build.make CMakeFiles/Koivisto.dir/src_files/eval.cpp.s
.PHONY : src_files/eval.cpp.s

src_files/main.o: src_files/main.cpp.o

.PHONY : src_files/main.o

# target to build an object file
src_files/main.cpp.o:
	$(MAKE) -f CMakeFiles/Koivisto.dir/build.make CMakeFiles/Koivisto.dir/src_files/main.cpp.o
.PHONY : src_files/main.cpp.o

src_files/main.i: src_files/main.cpp.i

.PHONY : src_files/main.i

# target to preprocess a source file
src_files/main.cpp.i:
	$(MAKE) -f CMakeFiles/Koivisto.dir/build.make CMakeFiles/Koivisto.dir/src_files/main.cpp.i
.PHONY : src_files/main.cpp.i

src_files/main.s: src_files/main.cpp.s

.PHONY : src_files/main.s

# target to generate assembly for a file
src_files/main.cpp.s:
	$(MAKE) -f CMakeFiles/Koivisto.dir/build.make CMakeFiles/Koivisto.dir/src_files/main.cpp.s
.PHONY : src_files/main.cpp.s

src_files/nn/DenseInput.o: src_files/nn/DenseInput.cpp.o

.PHONY : src_files/nn/DenseInput.o

# target to build an object file
src_files/nn/DenseInput.cpp.o:
	$(MAKE) -f CMakeFiles/Koivisto.dir/build.make CMakeFiles/Koivisto.dir/src_files/nn/DenseInput.cpp.o
.PHONY : src_files/nn/DenseInput.cpp.o

src_files/nn/DenseInput.i: src_files/nn/DenseInput.cpp.i

.PHONY : src_files/nn/DenseInput.i

# target to preprocess a source file
src_files/nn/DenseInput.cpp.i:
	$(MAKE) -f CMakeFiles/Koivisto.dir/build.make CMakeFiles/Koivisto.dir/src_files/nn/DenseInput.cpp.i
.PHONY : src_files/nn/DenseInput.cpp.i

src_files/nn/DenseInput.s: src_files/nn/DenseInput.cpp.s

.PHONY : src_files/nn/DenseInput.s

# target to generate assembly for a file
src_files/nn/DenseInput.cpp.s:
	$(MAKE) -f CMakeFiles/Koivisto.dir/build.make CMakeFiles/Koivisto.dir/src_files/nn/DenseInput.cpp.s
.PHONY : src_files/nn/DenseInput.cpp.s

src_files/nn/DenseLayer.o: src_files/nn/DenseLayer.cpp.o

.PHONY : src_files/nn/DenseLayer.o

# target to build an object file
src_files/nn/DenseLayer.cpp.o:
	$(MAKE) -f CMakeFiles/Koivisto.dir/build.make CMakeFiles/Koivisto.dir/src_files/nn/DenseLayer.cpp.o
.PHONY : src_files/nn/DenseLayer.cpp.o

src_files/nn/DenseLayer.i: src_files/nn/DenseLayer.cpp.i

.PHONY : src_files/nn/DenseLayer.i

# target to preprocess a source file
src_files/nn/DenseLayer.cpp.i:
	$(MAKE) -f CMakeFiles/Koivisto.dir/build.make CMakeFiles/Koivisto.dir/src_files/nn/DenseLayer.cpp.i
.PHONY : src_files/nn/DenseLayer.cpp.i

src_files/nn/DenseLayer.s: src_files/nn/DenseLayer.cpp.s

.PHONY : src_files/nn/DenseLayer.s

# target to generate assembly for a file
src_files/nn/DenseLayer.cpp.s:
	$(MAKE) -f CMakeFiles/Koivisto.dir/build.make CMakeFiles/Koivisto.dir/src_files/nn/DenseLayer.cpp.s
.PHONY : src_files/nn/DenseLayer.cpp.s

src_files/nn/DenseNetwork.o: src_files/nn/DenseNetwork.cpp.o

.PHONY : src_files/nn/DenseNetwork.o

# target to build an object file
src_files/nn/DenseNetwork.cpp.o:
	$(MAKE) -f CMakeFiles/Koivisto.dir/build.make CMakeFiles/Koivisto.dir/src_files/nn/DenseNetwork.cpp.o
.PHONY : src_files/nn/DenseNetwork.cpp.o

src_files/nn/DenseNetwork.i: src_files/nn/DenseNetwork.cpp.i

.PHONY : src_files/nn/DenseNetwork.i

# target to preprocess a source file
src_files/nn/DenseNetwork.cpp.i:
	$(MAKE) -f CMakeFiles/Koivisto.dir/build.make CMakeFiles/Koivisto.dir/src_files/nn/DenseNetwork.cpp.i
.PHONY : src_files/nn/DenseNetwork.cpp.i

src_files/nn/DenseNetwork.s: src_files/nn/DenseNetwork.cpp.s

.PHONY : src_files/nn/DenseNetwork.s

# target to generate assembly for a file
src_files/nn/DenseNetwork.cpp.s:
	$(MAKE) -f CMakeFiles/Koivisto.dir/build.make CMakeFiles/Koivisto.dir/src_files/nn/DenseNetwork.cpp.s
.PHONY : src_files/nn/DenseNetwork.cpp.s

src_files/nn/DenseOutput.o: src_files/nn/DenseOutput.cpp.o

.PHONY : src_files/nn/DenseOutput.o

# target to build an object file
src_files/nn/DenseOutput.cpp.o:
	$(MAKE) -f CMakeFiles/Koivisto.dir/build.make CMakeFiles/Koivisto.dir/src_files/nn/DenseOutput.cpp.o
.PHONY : src_files/nn/DenseOutput.cpp.o

src_files/nn/DenseOutput.i: src_files/nn/DenseOutput.cpp.i

.PHONY : src_files/nn/DenseOutput.i

# target to preprocess a source file
src_files/nn/DenseOutput.cpp.i:
	$(MAKE) -f CMakeFiles/Koivisto.dir/build.make CMakeFiles/Koivisto.dir/src_files/nn/DenseOutput.cpp.i
.PHONY : src_files/nn/DenseOutput.cpp.i

src_files/nn/DenseOutput.s: src_files/nn/DenseOutput.cpp.s

.PHONY : src_files/nn/DenseOutput.s

# target to generate assembly for a file
src_files/nn/DenseOutput.cpp.s:
	$(MAKE) -f CMakeFiles/Koivisto.dir/build.make CMakeFiles/Koivisto.dir/src_files/nn/DenseOutput.cpp.s
.PHONY : src_files/nn/DenseOutput.cpp.s

src_files/nn/data/CompactInput.o: src_files/nn/data/CompactInput.cpp.o

.PHONY : src_files/nn/data/CompactInput.o

# target to build an object file
src_files/nn/data/CompactInput.cpp.o:
	$(MAKE) -f CMakeFiles/Koivisto.dir/build.make CMakeFiles/Koivisto.dir/src_files/nn/data/CompactInput.cpp.o
.PHONY : src_files/nn/data/CompactInput.cpp.o

src_files/nn/data/CompactInput.i: src_files/nn/data/CompactInput.cpp.i

.PHONY : src_files/nn/data/CompactInput.i

# target to preprocess a source file
src_files/nn/data/CompactInput.cpp.i:
	$(MAKE) -f CMakeFiles/Koivisto.dir/build.make CMakeFiles/Koivisto.dir/src_files/nn/data/CompactInput.cpp.i
.PHONY : src_files/nn/data/CompactInput.cpp.i

src_files/nn/data/CompactInput.s: src_files/nn/data/CompactInput.cpp.s

.PHONY : src_files/nn/data/CompactInput.s

# target to generate assembly for a file
src_files/nn/data/CompactInput.cpp.s:
	$(MAKE) -f CMakeFiles/Koivisto.dir/build.make CMakeFiles/Koivisto.dir/src_files/nn/data/CompactInput.cpp.s
.PHONY : src_files/nn/data/CompactInput.cpp.s

src_files/search.o: src_files/search.cpp.o

.PHONY : src_files/search.o

# target to build an object file
src_files/search.cpp.o:
	$(MAKE) -f CMakeFiles/Koivisto.dir/build.make CMakeFiles/Koivisto.dir/src_files/search.cpp.o
.PHONY : src_files/search.cpp.o

src_files/search.i: src_files/search.cpp.i

.PHONY : src_files/search.i

# target to preprocess a source file
src_files/search.cpp.i:
	$(MAKE) -f CMakeFiles/Koivisto.dir/build.make CMakeFiles/Koivisto.dir/src_files/search.cpp.i
.PHONY : src_files/search.cpp.i

src_files/search.s: src_files/search.cpp.s

.PHONY : src_files/search.s

# target to generate assembly for a file
src_files/search.cpp.s:
	$(MAKE) -f CMakeFiles/Koivisto.dir/build.make CMakeFiles/Koivisto.dir/src_files/search.cpp.s
.PHONY : src_files/search.cpp.s

src_files/syzygy/tbchess.o: src_files/syzygy/tbchess.c.o

.PHONY : src_files/syzygy/tbchess.o

# target to build an object file
src_files/syzygy/tbchess.c.o:
	$(MAKE) -f CMakeFiles/Koivisto.dir/build.make CMakeFiles/Koivisto.dir/src_files/syzygy/tbchess.c.o
.PHONY : src_files/syzygy/tbchess.c.o

src_files/syzygy/tbchess.i: src_files/syzygy/tbchess.c.i

.PHONY : src_files/syzygy/tbchess.i

# target to preprocess a source file
src_files/syzygy/tbchess.c.i:
	$(MAKE) -f CMakeFiles/Koivisto.dir/build.make CMakeFiles/Koivisto.dir/src_files/syzygy/tbchess.c.i
.PHONY : src_files/syzygy/tbchess.c.i

src_files/syzygy/tbchess.s: src_files/syzygy/tbchess.c.s

.PHONY : src_files/syzygy/tbchess.s

# target to generate assembly for a file
src_files/syzygy/tbchess.c.s:
	$(MAKE) -f CMakeFiles/Koivisto.dir/build.make CMakeFiles/Koivisto.dir/src_files/syzygy/tbchess.c.s
.PHONY : src_files/syzygy/tbchess.c.s

src_files/syzygy/tbprobe.o: src_files/syzygy/tbprobe.c.o

.PHONY : src_files/syzygy/tbprobe.o

# target to build an object file
src_files/syzygy/tbprobe.c.o:
	$(MAKE) -f CMakeFiles/Koivisto.dir/build.make CMakeFiles/Koivisto.dir/src_files/syzygy/tbprobe.c.o
.PHONY : src_files/syzygy/tbprobe.c.o

src_files/syzygy/tbprobe.i: src_files/syzygy/tbprobe.c.i

.PHONY : src_files/syzygy/tbprobe.i

# target to preprocess a source file
src_files/syzygy/tbprobe.c.i:
	$(MAKE) -f CMakeFiles/Koivisto.dir/build.make CMakeFiles/Koivisto.dir/src_files/syzygy/tbprobe.c.i
.PHONY : src_files/syzygy/tbprobe.c.i

src_files/syzygy/tbprobe.s: src_files/syzygy/tbprobe.c.s

.PHONY : src_files/syzygy/tbprobe.s

# target to generate assembly for a file
src_files/syzygy/tbprobe.c.s:
	$(MAKE) -f CMakeFiles/Koivisto.dir/build.make CMakeFiles/Koivisto.dir/src_files/syzygy/tbprobe.c.s
.PHONY : src_files/syzygy/tbprobe.c.s

src_files/uci.o: src_files/uci.cpp.o

.PHONY : src_files/uci.o

# target to build an object file
src_files/uci.cpp.o:
	$(MAKE) -f CMakeFiles/Koivisto.dir/build.make CMakeFiles/Koivisto.dir/src_files/uci.cpp.o
.PHONY : src_files/uci.cpp.o

src_files/uci.i: src_files/uci.cpp.i

.PHONY : src_files/uci.i

# target to preprocess a source file
src_files/uci.cpp.i:
	$(MAKE) -f CMakeFiles/Koivisto.dir/build.make CMakeFiles/Koivisto.dir/src_files/uci.cpp.i
.PHONY : src_files/uci.cpp.i

src_files/uci.s: src_files/uci.cpp.s

.PHONY : src_files/uci.s

# target to generate assembly for a file
src_files/uci.cpp.s:
	$(MAKE) -f CMakeFiles/Koivisto.dir/build.make CMakeFiles/Koivisto.dir/src_files/uci.cpp.s
.PHONY : src_files/uci.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... Koivisto"
	@echo "... src_files/Bitboard.o"
	@echo "... src_files/Bitboard.i"
	@echo "... src_files/Bitboard.s"
	@echo "... src_files/Board.o"
	@echo "... src_files/Board.i"
	@echo "... src_files/Board.s"
	@echo "... src_files/History.o"
	@echo "... src_files/History.i"
	@echo "... src_files/History.s"
	@echo "... src_files/Move.o"
	@echo "... src_files/Move.i"
	@echo "... src_files/Move.s"
	@echo "... src_files/MoveOrderer.o"
	@echo "... src_files/MoveOrderer.i"
	@echo "... src_files/MoveOrderer.s"
	@echo "... src_files/Perft.o"
	@echo "... src_files/Perft.i"
	@echo "... src_files/Perft.s"
	@echo "... src_files/TimeManager.o"
	@echo "... src_files/TimeManager.i"
	@echo "... src_files/TimeManager.s"
	@echo "... src_files/TranspositionTable.o"
	@echo "... src_files/TranspositionTable.i"
	@echo "... src_files/TranspositionTable.s"
	@echo "... src_files/Tuning.o"
	@echo "... src_files/Tuning.i"
	@echo "... src_files/Tuning.s"
	@echo "... src_files/Util.o"
	@echo "... src_files/Util.i"
	@echo "... src_files/Util.s"
	@echo "... src_files/eval.o"
	@echo "... src_files/eval.i"
	@echo "... src_files/eval.s"
	@echo "... src_files/main.o"
	@echo "... src_files/main.i"
	@echo "... src_files/main.s"
	@echo "... src_files/nn/DenseInput.o"
	@echo "... src_files/nn/DenseInput.i"
	@echo "... src_files/nn/DenseInput.s"
	@echo "... src_files/nn/DenseLayer.o"
	@echo "... src_files/nn/DenseLayer.i"
	@echo "... src_files/nn/DenseLayer.s"
	@echo "... src_files/nn/DenseNetwork.o"
	@echo "... src_files/nn/DenseNetwork.i"
	@echo "... src_files/nn/DenseNetwork.s"
	@echo "... src_files/nn/DenseOutput.o"
	@echo "... src_files/nn/DenseOutput.i"
	@echo "... src_files/nn/DenseOutput.s"
	@echo "... src_files/nn/data/CompactInput.o"
	@echo "... src_files/nn/data/CompactInput.i"
	@echo "... src_files/nn/data/CompactInput.s"
	@echo "... src_files/search.o"
	@echo "... src_files/search.i"
	@echo "... src_files/search.s"
	@echo "... src_files/syzygy/tbchess.o"
	@echo "... src_files/syzygy/tbchess.i"
	@echo "... src_files/syzygy/tbchess.s"
	@echo "... src_files/syzygy/tbprobe.o"
	@echo "... src_files/syzygy/tbprobe.i"
	@echo "... src_files/syzygy/tbprobe.s"
	@echo "... src_files/uci.o"
	@echo "... src_files/uci.i"
	@echo "... src_files/uci.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

