name: C/C++ CI

on:
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Ubuntu:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        compiler: [g++-9]
        target: [openbench, native, valgrind]

    steps:
      - uses: actions/checkout@v2

      - name: Create build
        run: |
         cd src_files
         make ${{ matrix.target }} CXX=${{ matrix.compiler }} EXE=../bin/Koivisto
      - name: Check valgrind
        if: matrix.target == 'valgrind'
        run: |
         sudo apt-get install g++
         sudo apt update
         sudo apt install expect valgrind g++-multilib qemu-user
         cd bin
         valgrind --error-exitcode=1 ./Koivisto bench
      - name: Check bench matches commit message
        if: matrix.target == 'openbench' && github.event_name == 'push'
        run: |
          cd bin
          commit_bench=$(git show --summary | grep -o "bench: [0-9]*" | awk '{ print $NF }')
          ./Koivisto bench > bench.txt
          actual_bench=$(grep -i OVERALL: bench.txt | awk -F'[^0-9]+' '{ print $2 }')
          if [[ "$actual_bench" != "$commit_bench" ]]; then echo "Incorrect bench, got '$actual_bench' expected '$commit_bench'" && exit 1; fi

  Windows:
    runs-on: windows-2022

    strategy:
      matrix:
        config:
          - { system: mingw64, package: x86_64-gcc, compiler: g++ }
        target: [openbench, native]

    steps:
      - uses: actions/checkout@v2
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{matrix.config.system}}
          install: mingw-w64-${{matrix.config.package}} make git

      - name: Add compiler to $PATH env
        shell: bash
        run: echo "PATH=$PATH:/c/msys64/${{ matrix.config.system }}/bin" >> $GITHUB_ENV

      - name: Create build
        shell: msys2 {0}
        run: |
         cd src_files
         make ${{ matrix.target }} CXX=${{ matrix.config.compiler }} EXE=../bin/Koivisto

      - name: Check bench matches commit message
        if: matrix.target == 'openbench' && github.event_name == 'push'
        shell: msys2 {0}
        run: |
          cd bin
          commit_bench=$(git show --summary | grep -o "bench: [0-9]*" | awk '{ print $NF }')
          ./Koivisto bench > bench.txt
          actual_bench=$(grep -i OVERALL: bench.txt | awk -F'[^0-9]+' '{ print $2 }')
          if [[ "$actual_bench" != "$commit_bench" ]]; then echo "Incorrect bench, got '$actual_bench' expected '$commit_bench'" && exit 1; fi
